//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package getreply_gk

import (
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/memkv/error_gk"
)

type S struct {
	Err   error_gk.E
	Value []byte
}

func Marshal(enc []byte, g S) []byte {
	enc = error_gk.Marshal(enc, g.Err)
	enc = marshal.WriteInt(enc, uint64(len(g.Value)))
	enc = marshal.WriteBytes(enc, g.Value)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	err, s := error_gk.Unmarshal(s)
	valueBytes, s := marshal.ReadLenPrefixedBytes(s)
	value := std.BytesClone(valueBytes)

	return S{
		Err:   err,
		Value: value,
	}, s
}
