//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package getargs_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Epoch uint64
}

func Marshal(enc []byte, g S) []byte {
	enc = marshal.WriteInt(enc, g.Epoch)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	epoch, s := marshal.ReadInt(s)

	return S{
		Epoch: epoch,
	}, s
}
