//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package configuration_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Replicas []uint64
}

func Marshal(enc []byte, c S) []byte {

	enc = marshal.WriteInt(enc, uint64(len(c.Replicas)))
	enc = marshal.WriteSlice[uint64](enc, c.Replicas, marshal.WriteInt)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	replicasLen, s := marshal.ReadInt(s)
	replicas, s := marshal.ReadSlice[uint64](s, replicasLen, marshal.ReadInt)

	return S{
		Replicas: replicas,
	}, s
}
