//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package getargs_gk

import (
	"github.com/goose-lang/primitive"
	"github.com/goose-lang/std"
)

type S struct {
	Get string
}

func Marshal(enc []byte, g S) []byte {
	primitive.AssumeNoStringOverflow(g.Get)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(g.Get))

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	getBytes, s := marshal.ReadLenPrefixedBytes(s)
	get := string(std.BytesClone(getBytes))

	return S{
		Get: get,
	}, s
}
