//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package lockrequest_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Id uint64
}

func Marshal(enc []byte, l S) []byte {
	enc = marshal.WriteInt(enc, l.Id)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	id, s := marshal.ReadInt(s)

	return S{
		Id: id,
	}, s
}
