//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package trycommitreply_gk

import (
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/paxi/reconf/error_gk"
)

type S struct {
	Err     error_gk.E
	Version uint64
}

func Marshal(enc []byte, t S) []byte {
	enc = error_gk.Marshal(enc, t.Err)
	enc = marshal.WriteInt(enc, t.Version)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	err, s := error_gk.Unmarshal(s)
	version, s := marshal.ReadInt(s)

	return S{
		Err:     err,
		Version: version,
	}, s
}
