//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package enternewepochreply_gk

import (
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/vrsm/paxos/error_gk"
)

type S struct {
	Err           error_gk.E
	AcceptedEpoch uint64
	NextIndex     uint64
	State         []byte
}

func Marshal(enc []byte, e S) []byte {
	enc = error_gk.Marshal(enc, e.Err)
	enc = marshal.WriteInt(enc, e.AcceptedEpoch)
	enc = marshal.WriteInt(enc, e.NextIndex)
	enc = marshal.WriteInt(enc, uint64(len(e.State)))
	enc = marshal.WriteBytes(enc, e.State)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	err, s := error_gk.Unmarshal(s)
	acceptedEpoch, s := marshal.ReadInt(s)
	nextIndex, s := marshal.ReadInt(s)
	stateBytes, s := marshal.ReadLenPrefixedBytes(s)
	state := std.BytesClone(stateBytes)

	return S{
		Err:           err,
		AcceptedEpoch: acceptedEpoch,
		NextIndex:     nextIndex,
		State:         state,
	}, s
}
