//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package conditionalputreply_gk

import (
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/memkv/error_gk"
)

type S struct {
	Err     error_gk.E
	Success bool
}

func Marshal(enc []byte, c S) []byte {
	enc = error_gk.Marshal(enc, c.Err)
	enc = marshal.WriteBool(enc, c.Success)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	err, s := error_gk.Unmarshal(s)
	success, s := marshal.ReadBool(s)

	return S{
		Err:     err,
		Success: success,
	}, s
}
