//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package preparereply_gk

import (
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/paxi/reconf/error_gk"
	"github.com/mit-pdos/gokv/paxi/reconf/monotonicvalue_gk"
)

type S struct {
	Err  error_gk.E
	Term uint64
	Val  monotonicvalue_gk.S
}

func Marshal(enc []byte, p S) []byte {
	enc = error_gk.Marshal(enc, p.Err)
	enc = marshal.WriteInt(enc, p.Term)
	enc = monotonicvalue_gk.Marshal(enc, p.Val)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	err, s := error_gk.Unmarshal(s)
	term, s := marshal.ReadInt(s)
	val, s := monotonicvalue_gk.Unmarshal(s)

	return S{
		Err:  err,
		Term: term,
		Val:  val,
	}, s
}
