//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package becomeprimaryargs_gk

import (
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/reconfig/replica/configuration_gk"
)

type S struct {
	Epoch uint64
	Conf  configuration_gk.S
}

func Marshal(enc []byte, b S) []byte {
	enc = marshal.WriteInt(enc, b.Epoch)
	enc = configuration_gk.Marshal(enc, b.Conf)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	epoch, s := marshal.ReadInt(s)
	conf, s := configuration_gk.Unmarshal(s)

	return S{
		Epoch: epoch,
		Conf:  conf,
	}, s
}
