//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package applyasfollowerreply_gk

import (
	"github.com/mit-pdos/gokv/vrsm/paxos/error_gk"
)

type S struct {
	Err error_gk.E
}

func Marshal(enc []byte, a S) []byte {
	enc = error_gk.Marshal(enc, a.Err)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	err, s := error_gk.Unmarshal(s)

	return S{
		Err: err,
	}, s
}
