//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package state_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Epoch             uint64
	ReservedEpoch     uint64
	LeaseExpiration   uint64
	WantLeaseToExpire bool
	Config            []uint64
}

func Marshal(enc []byte, s S) []byte {
	enc = marshal.WriteInt(enc, s.Epoch)
	enc = marshal.WriteInt(enc, s.ReservedEpoch)
	enc = marshal.WriteInt(enc, s.LeaseExpiration)
	enc = marshal.WriteBool(enc, s.WantLeaseToExpire)

	enc = marshal.WriteInt(enc, uint64(len(s.Config)))
	enc = marshal.WriteSlice[uint64](enc, s.Config, marshal.WriteInt)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	epoch, s := marshal.ReadInt(s)
	reservedEpoch, s := marshal.ReadInt(s)
	leaseExpiration, s := marshal.ReadInt(s)
	wantLeaseToExpire, s := marshal.ReadBool(s)
	configLen, s := marshal.ReadInt(s)
	config, s := marshal.ReadSlice[uint64](s, configLen, marshal.ReadInt)

	return S{
		Epoch:             epoch,
		ReservedEpoch:     reservedEpoch,
		LeaseExpiration:   leaseExpiration,
		WantLeaseToExpire: wantLeaseToExpire,
		Config:            config,
	}, s
}
