//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package condputargs_gk

import (
	"github.com/goose-lang/primitive"
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	Key    string
	Expect string
	Val    string
}

func Marshal(enc []byte, c S) []byte {
	primitive.AssumeNoStringOverflow(c.Key)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(c.Key))
	primitive.AssumeNoStringOverflow(c.Expect)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(c.Expect))
	primitive.AssumeNoStringOverflow(c.Val)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(c.Val))

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	keyBytes, s := marshal.ReadLenPrefixedBytes(s)
	key := string(std.BytesClone(keyBytes))
	expectBytes, s := marshal.ReadLenPrefixedBytes(s)
	expect := string(std.BytesClone(expectBytes))
	valBytes, s := marshal.ReadLenPrefixedBytes(s)
	val := string(std.BytesClone(valBytes))

	return S{
		Key:    key,
		Expect: expect,
		Val:    val,
	}, s
}
