//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package getlogreply_gk

import (
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/reconfig/replica/error_gk"
	"github.com/mit-pdos/gokv/reconfig/replica/logentry_gk"
)

type S struct {
	Err        error_gk.E
	Log        []logentry_gk.S
	StartIndex uint64
}

func Marshal(enc []byte, g S) []byte {
	enc = error_gk.Marshal(enc, g.Err)

	enc = marshal.WriteInt(enc, uint64(len(g.Log)))
	enc = marshal.WriteSlice[logentry_gk.S](enc, g.Log, logentry_gk.Marshal)
	enc = marshal.WriteInt(enc, g.StartIndex)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	err, s := error_gk.Unmarshal(s)
	logLen, s := marshal.ReadInt(s)
	log, s := marshal.ReadSlice[logentry_gk.S](s, logLen, logentry_gk.Unmarshal)
	startIndex, s := marshal.ReadInt(s)

	return S{
		Err:        err,
		Log:        log,
		StartIndex: startIndex,
	}, s
}
