//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package putargs_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Epoch uint64
	V     uint64
}

func Marshal(enc []byte, p S) []byte {
	enc = marshal.WriteInt(enc, p.Epoch)
	enc = marshal.WriteInt(enc, p.V)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	epoch, s := marshal.ReadInt(s)
	v, s := marshal.ReadInt(s)

	return S{
		Epoch: epoch,
		V:     v,
	}, s
}
