//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package monotonicvalue_gk

import (
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/paxi/reconf/config_gk"
)

type S struct {
	Version uint64
	Val     []byte
	Conf    config_gk.S
}

func Marshal(enc []byte, m S) []byte {
	enc = marshal.WriteInt(enc, m.Version)
	enc = marshal.WriteInt(enc, uint64(len(m.Val)))
	enc = marshal.WriteBytes(enc, m.Val)
	enc = config_gk.Marshal(enc, m.Conf)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	version, s := marshal.ReadInt(s)
	valBytes, s := marshal.ReadLenPrefixedBytes(s)
	val := std.BytesClone(valBytes)
	conf, s := config_gk.Unmarshal(s)

	return S{
		Version: version,
		Val:     val,
		Conf:    conf,
	}, s
}
