//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package recordchunk_gk

import (
	"github.com/goose-lang/primitive"
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	WriteId     uint64
	Server      uint64
	ContentHash string
	Index       uint64
}

func Marshal(enc []byte, r S) []byte {
	enc = marshal.WriteInt(enc, r.WriteId)
	enc = marshal.WriteInt(enc, r.Server)
	primitive.AssumeNoStringOverflow(r.ContentHash)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(r.ContentHash))
	enc = marshal.WriteInt(enc, r.Index)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	writeId, s := marshal.ReadInt(s)
	server, s := marshal.ReadInt(s)
	contentHashBytes, s := marshal.ReadLenPrefixedBytes(s)
	contentHash := string(std.BytesClone(contentHashBytes))
	index, s := marshal.ReadInt(s)

	return S{
		WriteId:     writeId,
		Server:      server,
		ContentHash: contentHash,
		Index:       index,
	}, s
}
