//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package get_gk

import (
	"github.com/goose-lang/primitive"
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	OpId uint64
	Key  string
}

func Marshal(enc []byte, g S) []byte {
	enc = marshal.WriteInt(enc, g.OpId)
	primitive.AssumeNoStringOverflow(g.Key)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(g.Key))

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	opId, s := marshal.ReadInt(s)
	keyBytes, s := marshal.ReadLenPrefixedBytes(s)
	key := string(std.BytesClone(keyBytes))

	return S{
		OpId: opId,
		Key:  key,
	}, s
}
