//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package configuration_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Addrs []uint64
}

func Marshal(enc []byte, c S) []byte {

	enc = marshal.WriteInt(enc, uint64(len(c.Addrs)))
	enc = marshal.WriteSlice[uint64](enc, c.Addrs, marshal.WriteInt)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	addrsLen, s := marshal.ReadInt(s)
	addrs, s := marshal.ReadSlice[uint64](s, addrsLen, marshal.ReadInt)

	return S{
		Addrs: addrs,
	}, s
}
