//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package logentry_gk

import (
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	Entry []byte
}

func Marshal(enc []byte, l S) []byte {
	enc = marshal.WriteInt(enc, uint64(len(l.Entry)))
	enc = marshal.WriteBytes(enc, l.Entry)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	entryBytes, s := marshal.ReadLenPrefixedBytes(s)
	entry := std.BytesClone(entryBytes)

	return S{
		Entry: entry,
	}, s
}
