//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package applyreply_gk

import (
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/vrsm/replica/err_gk"
)

type S struct {
	Err   err_gk.E
	Reply []byte
}

func Marshal(enc []byte, a S) []byte {
	enc = err_gk.Marshal(enc, a.Err)
	enc = marshal.WriteInt(enc, uint64(len(a.Reply)))
	enc = marshal.WriteBytes(enc, a.Reply)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	err, s := err_gk.Unmarshal(s)
	replyBytes, s := marshal.ReadLenPrefixedBytes(s)
	reply := std.BytesClone(replyBytes)

	return S{
		Err:   err,
		Reply: reply,
	}, s
}
