//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package chunkhandle_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Addr        uint64
	ContentHash string
}

func Marshal(c S, prefix []byte) []byte {
	var enc = prefix

	enc = marshal.WriteInt(enc, c.Addr)
	contenthashBytes := []byte(c.ContentHash)
	enc = marshal.WriteInt(enc, uint64(len(contenthashBytes)))
	enc = marshal.WriteBytes(enc, contenthashBytes)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {
	var enc = s // Needed for goose compatibility
	var addr uint64
	var contentHash string

	addr, enc = marshal.ReadInt(enc)
	var contentHashLen uint64
	var contentHashBytes []byte
	contentHashLen, enc = marshal.ReadInt(enc)
	contentHashBytes, enc = marshal.ReadBytesCopy(enc, contentHashLen)
	contentHash = string(contentHashBytes)

	return S{
		Addr:        addr,
		ContentHash: contentHash,
	}, enc
}
