//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package chunkhandle_gk

import (
	"github.com/goose-lang/primitive"
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	Addr        uint64
	ContentHash string
}

func Marshal(enc []byte, c S) []byte {
	enc = marshal.WriteInt(enc, c.Addr)
	primitive.AssumeNoStringOverflow(c.ContentHash)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(c.ContentHash))

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	addr, s := marshal.ReadInt(s)
	contentHashBytes, s := marshal.ReadLenPrefixedBytes(s)
	contentHash := string(std.BytesClone(contentHashBytes))

	return S{
		Addr:        addr,
		ContentHash: contentHash,
	}, s
}
