//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package proposeargs_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Pn          uint64
	CommitIndex uint64
	Log         []uint64
}

func Marshal(enc []byte, p S) []byte {
	enc = marshal.WriteInt(enc, p.Pn)
	enc = marshal.WriteInt(enc, p.CommitIndex)

	enc = marshal.WriteInt(enc, uint64(len(p.Log)))
	enc = marshal.WriteSlice[uint64](enc, p.Log, marshal.WriteInt)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	pn, s := marshal.ReadInt(s)
	commitIndex, s := marshal.ReadInt(s)
	logLen, s := marshal.ReadInt(s)
	log, s := marshal.ReadSlice[uint64](s, logLen, marshal.ReadInt)

	return S{
		Pn:          pn,
		CommitIndex: commitIndex,
		Log:         log,
	}, s
}
