//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package putargs_gk

import (
	"github.com/goose-lang/primitive"
	"github.com/goose-lang/std"
)

type S struct {
	Key string
	Val string
}

func Marshal(enc []byte, p S) []byte {
	primitive.AssumeNoStringOverflow(p.Key)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(p.Key))
	primitive.AssumeNoStringOverflow(p.Val)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(p.Val))

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	keyBytes, s := marshal.ReadLenPrefixedBytes(s)
	key := string(std.BytesClone(keyBytes))
	valBytes, s := marshal.ReadLenPrefixedBytes(s)
	val := string(std.BytesClone(valBytes))

	return S{
		Key: key,
		Val: val,
	}, s
}
