//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package increasecommitargs_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	V uint64
}

func Marshal(enc []byte, i S) []byte {
	enc = marshal.WriteInt(enc, i.V)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	v, s := marshal.ReadInt(s)

	return S{
		V: v,
	}, s
}
