//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package moveshardrequest_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Sid uint64
	Dst uint64
}

func Marshal(enc []byte, m S) []byte {
	enc = marshal.WriteInt(enc, m.Sid)
	enc = marshal.WriteInt(enc, m.Dst)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	sid, s := marshal.ReadInt(s)
	dst, s := marshal.ReadInt(s)

	return S{
		Sid: sid,
		Dst: dst,
	}, s
}
