//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package putrequest_gk

import (
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	Key   uint64
	Value []byte
}

func Marshal(enc []byte, p S) []byte {
	enc = marshal.WriteInt(enc, p.Key)
	enc = marshal.WriteInt(enc, uint64(len(p.Value)))
	enc = marshal.WriteBytes(enc, p.Value)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	key, s := marshal.ReadInt(s)
	valueBytes, s := marshal.ReadLenPrefixedBytes(s)
	value := std.BytesClone(valueBytes)

	return S{
		Key:   key,
		Value: value,
	}, s
}
