//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package applyasfollowerargs_gk

import (
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	Epoch     uint64
	NextIndex uint64
	State     []byte
}

func Marshal(enc []byte, a S) []byte {
	enc = marshal.WriteInt(enc, a.Epoch)
	enc = marshal.WriteInt(enc, a.NextIndex)
	enc = marshal.WriteInt(enc, uint64(len(a.State)))
	enc = marshal.WriteBytes(enc, a.State)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	epoch, s := marshal.ReadInt(s)
	nextIndex, s := marshal.ReadInt(s)
	stateBytes, s := marshal.ReadLenPrefixedBytes(s)
	state := std.BytesClone(stateBytes)

	return S{
		Epoch:     epoch,
		NextIndex: nextIndex,
		State:     state,
	}, s
}
