//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package preparedread_gk

import (
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/tutorial/objectstore/dir/chunkhandle_gk"
)

type S struct {
	Handles []chunkhandle_gk.S
}

func Marshal(enc []byte, p S) []byte {

	enc = marshal.WriteInt(enc, uint64(len(p.Handles)))
	enc = marshal.WriteSlice[chunkhandle_gk.S](enc, p.Handles, chunkhandle_gk.Marshal)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	handlesLen, s := marshal.ReadInt(s)
	handles, s := marshal.ReadSlice[chunkhandle_gk.S](s, handlesLen, chunkhandle_gk.Unmarshal)

	return S{
		Handles: handles,
	}, s
}
