//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package applyasbackupargs_gk

import (
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	Epoch uint64
	Index uint64
	Op    []byte
}

func Marshal(enc []byte, a S) []byte {
	enc = marshal.WriteInt(enc, a.Epoch)
	enc = marshal.WriteInt(enc, a.Index)
	enc = marshal.WriteInt(enc, uint64(len(a.Op)))
	enc = marshal.WriteBytes(enc, a.Op)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	epoch, s := marshal.ReadInt(s)
	index, s := marshal.ReadInt(s)
	opBytes, s := marshal.ReadLenPrefixedBytes(s)
	op := std.BytesClone(opBytes)

	return S{
		Epoch: epoch,
		Index: index,
		Op:    op,
	}, s
}
