//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package setstateargs_gk

import (
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	Epoch              uint64
	NextIndex          uint64
	CommittedNextIndex uint64
	State              []byte
}

func Marshal(enc []byte, s S) []byte {
	enc = marshal.WriteInt(enc, s.Epoch)
	enc = marshal.WriteInt(enc, s.NextIndex)
	enc = marshal.WriteInt(enc, s.CommittedNextIndex)
	enc = marshal.WriteInt(enc, uint64(len(s.State)))
	enc = marshal.WriteBytes(enc, s.State)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	epoch, s := marshal.ReadInt(s)
	nextIndex, s := marshal.ReadInt(s)
	committedNextIndex, s := marshal.ReadInt(s)
	stateBytes, s := marshal.ReadLenPrefixedBytes(s)
	state := std.BytesClone(stateBytes)

	return S{
		Epoch:              epoch,
		NextIndex:          nextIndex,
		CommittedNextIndex: committedNextIndex,
		State:              state,
	}, s
}
