//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package getreply_gk

import (
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/fencing/ctr/error_gk"
)

type S struct {
	Err error_gk.E
	Val uint64
}

func Marshal(enc []byte, g S) []byte {
	enc = error_gk.Marshal(enc, g.Err)
	enc = marshal.WriteInt(enc, g.Val)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	err, s := error_gk.Unmarshal(s)
	val, s := marshal.ReadInt(s)

	return S{
		Err: err,
		Val: val,
	}, s
}
