//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package paxosstate_gk

import (
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	Epoch         uint64
	AcceptedEpoch uint64
	NextIndex     uint64
	State         []byte
	IsLeader      bool
}

func Marshal(enc []byte, p S) []byte {
	enc = marshal.WriteInt(enc, p.Epoch)
	enc = marshal.WriteInt(enc, p.AcceptedEpoch)
	enc = marshal.WriteInt(enc, p.NextIndex)
	enc = marshal.WriteInt(enc, uint64(len(p.State)))
	enc = marshal.WriteBytes(enc, p.State)
	enc = marshal.WriteBool(enc, p.IsLeader)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	epoch, s := marshal.ReadInt(s)
	acceptedEpoch, s := marshal.ReadInt(s)
	nextIndex, s := marshal.ReadInt(s)
	stateBytes, s := marshal.ReadLenPrefixedBytes(s)
	state := std.BytesClone(stateBytes)
	isLeader, s := marshal.ReadBool(s)

	return S{
		Epoch:         epoch,
		AcceptedEpoch: acceptedEpoch,
		NextIndex:     nextIndex,
		State:         state,
		IsLeader:      isLeader,
	}, s
}
