//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package writechunk_gk

import (
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	WriteId uint64
	Chunk   []byte
	Index   uint64
}

func Marshal(enc []byte, w S) []byte {
	enc = marshal.WriteInt(enc, w.WriteId)
	enc = marshal.WriteInt(enc, uint64(len(w.Chunk)))
	enc = marshal.WriteBytes(enc, w.Chunk)
	enc = marshal.WriteInt(enc, w.Index)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	writeId, s := marshal.ReadInt(s)
	chunkBytes, s := marshal.ReadLenPrefixedBytes(s)
	chunk := std.BytesClone(chunkBytes)
	index, s := marshal.ReadInt(s)

	return S{
		WriteId: writeId,
		Chunk:   chunk,
		Index:   index,
	}, s
}
