//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package applyreply_gk

import (
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/vrsm/paxos/error_gk"
)

type S struct {
	Err error_gk.E
	Ret []byte
}

func Marshal(enc []byte, a S) []byte {
	enc = error_gk.Marshal(enc, a.Err)
	enc = marshal.WriteInt(enc, uint64(len(a.Ret)))
	enc = marshal.WriteBytes(enc, a.Ret)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	err, s := error_gk.Unmarshal(s)
	retBytes, s := marshal.ReadLenPrefixedBytes(s)
	ret := std.BytesClone(retBytes)

	return S{
		Err: err,
		Ret: ret,
	}, s
}
