//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package preparedwrite_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Id         uint64
	ChunkAddrs []uint64
}

func Marshal(enc []byte, p S) []byte {
	enc = marshal.WriteInt(enc, p.Id)

	enc = marshal.WriteInt(enc, uint64(len(p.ChunkAddrs)))
	enc = marshal.WriteSlice[uint64](enc, p.ChunkAddrs, marshal.WriteInt)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	id, s := marshal.ReadInt(s)
	chunkAddrsLen, s := marshal.ReadInt(s)
	chunkAddrs, s := marshal.ReadSlice[uint64](s, chunkAddrsLen, marshal.ReadInt)

	return S{
		Id:         id,
		ChunkAddrs: chunkAddrs,
	}, s
}
