//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package preparedwrite_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Id         uint64
	CheckAddrs []uint64
}

func Marshal(enc []byte, p S) []byte {
	enc = marshal.WriteInt(enc, p.Id)

	enc = marshal.WriteInt(enc, uint64(len(p.CheckAddrs)))
	enc = marshal.WriteSlice[uint64](enc, p.CheckAddrs, marshal.WriteInt)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	id, s := marshal.ReadInt(s)
	checkAddrsLen, s := marshal.ReadInt(s)
	checkAddrs, s := marshal.ReadSlice[uint64](s, checkAddrsLen, marshal.ReadInt)

	return S{
		Id:         id,
		CheckAddrs: checkAddrs,
	}, s
}
