//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package shardmap_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Shards []uint64
}

func Marshal(enc []byte, s S) []byte {

	enc = marshal.WriteInt(enc, uint64(len(s.Shards)))
	enc = marshal.WriteSlice[uint64](enc, s.Shards, marshal.WriteInt)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	shardsLen, s := marshal.ReadInt(s)
	shards, s := marshal.ReadSlice[uint64](s, shardsLen, marshal.ReadInt)

	return S{
		Shards: shards,
	}, s
}
