//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package conditionalput_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	OpId        uint64
	Key         string
	ExpectedVal string
	NewVal      string
}

func Marshal(prefix []byte, c S) []byte {
	var enc = prefix

	enc = marshal.WriteInt(enc, c.OpId)
	keyBytes := []byte(c.Key)
	enc = marshal.WriteInt(enc, uint64(len(keyBytes)))
	enc = marshal.WriteBytes(enc, keyBytes)
	expectedvalBytes := []byte(c.ExpectedVal)
	enc = marshal.WriteInt(enc, uint64(len(expectedvalBytes)))
	enc = marshal.WriteBytes(enc, expectedvalBytes)
	newvalBytes := []byte(c.NewVal)
	enc = marshal.WriteInt(enc, uint64(len(newvalBytes)))
	enc = marshal.WriteBytes(enc, newvalBytes)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {
	var enc = s // Needed for goose compatibility
	var opId uint64
	var key string
	var expectedVal string
	var newVal string

	opId, enc = marshal.ReadInt(enc)
	var keyLen uint64
	var keyBytes []byte
	keyLen, enc = marshal.ReadInt(enc)
	keyBytes, enc = marshal.ReadBytesCopy(enc, keyLen)
	key = string(keyBytes)
	var expectedValLen uint64
	var expectedValBytes []byte
	expectedValLen, enc = marshal.ReadInt(enc)
	expectedValBytes, enc = marshal.ReadBytesCopy(enc, expectedValLen)
	expectedVal = string(expectedValBytes)
	var newValLen uint64
	var newValBytes []byte
	newValLen, enc = marshal.ReadInt(enc)
	newValBytes, enc = marshal.ReadBytesCopy(enc, newValLen)
	newVal = string(newValBytes)

	return S{
		OpId:        opId,
		Key:         key,
		ExpectedVal: expectedVal,
		NewVal:      newVal,
	}, enc
}
