//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package conditionalput_gk

import (
	"github.com/goose-lang/primitive"
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	OpId        uint64
	Key         string
	ExpectedVal string
	NewVal      string
}

func Marshal(enc []byte, c S) []byte {
	enc = marshal.WriteInt(enc, c.OpId)
	primitive.AssumeNoStringOverflow(c.Key)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(c.Key))
	primitive.AssumeNoStringOverflow(c.ExpectedVal)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(c.ExpectedVal))
	primitive.AssumeNoStringOverflow(c.NewVal)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(c.NewVal))

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	opId, s := marshal.ReadInt(s)
	keyBytes, s := marshal.ReadLenPrefixedBytes(s)
	key := string(std.BytesClone(keyBytes))
	expectedValBytes, s := marshal.ReadLenPrefixedBytes(s)
	expectedVal := string(std.BytesClone(expectedValBytes))
	newValBytes, s := marshal.ReadLenPrefixedBytes(s)
	newVal := string(std.BytesClone(newValBytes))

	return S{
		OpId:        opId,
		Key:         key,
		ExpectedVal: expectedVal,
		NewVal:      newVal,
	}, s
}
