//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package appendargs_gk

import (
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/reconfig/replica/logentry_gk"
)

type S struct {
	Epoch uint64
	Entry logentry_gk.S
	Index uint64
}

func Marshal(enc []byte, a S) []byte {
	enc = marshal.WriteInt(enc, a.Epoch)
	enc = logentry_gk.Marshal(enc, a.Entry)
	enc = marshal.WriteInt(enc, a.Index)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	epoch, s := marshal.ReadInt(s)
	entry, s := logentry_gk.Unmarshal(s)
	index, s := marshal.ReadInt(s)

	return S{
		Epoch: epoch,
		Entry: entry,
		Index: index,
	}, s
}
