//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package conditionalputrequest_gk

import (
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	Key           uint64
	ExpectedValue []byte
	NewValue      []byte
}

func Marshal(enc []byte, c S) []byte {
	enc = marshal.WriteInt(enc, c.Key)
	enc = marshal.WriteInt(enc, uint64(len(c.ExpectedValue)))
	enc = marshal.WriteBytes(enc, c.ExpectedValue)
	enc = marshal.WriteInt(enc, uint64(len(c.NewValue)))
	enc = marshal.WriteBytes(enc, c.NewValue)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	key, s := marshal.ReadInt(s)
	expectedValueBytes, s := marshal.ReadLenPrefixedBytes(s)
	expectedValue := std.BytesClone(expectedValueBytes)
	newValueBytes, s := marshal.ReadLenPrefixedBytes(s)
	newValue := std.BytesClone(newValueBytes)

	return S{
		Key:           key,
		ExpectedValue: expectedValue,
		NewValue:      newValue,
	}, s
}
