//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package config_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Members     []uint64
	NextMembers []uint64
}

func Marshal(enc []byte, c S) []byte {

	enc = marshal.WriteInt(enc, uint64(len(c.Members)))
	enc = marshal.WriteSlice[uint64](enc, c.Members, marshal.WriteInt)

	enc = marshal.WriteInt(enc, uint64(len(c.NextMembers)))
	enc = marshal.WriteSlice[uint64](enc, c.NextMembers, marshal.WriteInt)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	membersLen, s := marshal.ReadInt(s)
	members, s := marshal.ReadSlice[uint64](s, membersLen, marshal.ReadInt)
	nextMembersLen, s := marshal.ReadInt(s)
	nextMembers, s := marshal.ReadSlice[uint64](s, nextMembersLen, marshal.ReadInt)

	return S{
		Members:     members,
		NextMembers: nextMembers,
	}, s
}
