//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package becomereplicaargs_gk

import (
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/reconfig/replica/logentry_gk"
)

type S struct {
	Epoch      uint64
	StartIndex uint64
	Log        []logentry_gk.S
}

func Marshal(enc []byte, b S) []byte {
	enc = marshal.WriteInt(enc, b.Epoch)
	enc = marshal.WriteInt(enc, b.StartIndex)

	enc = marshal.WriteInt(enc, uint64(len(b.Log)))
	enc = marshal.WriteSlice[logentry_gk.S](enc, b.Log, logentry_gk.Marshal)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	epoch, s := marshal.ReadInt(s)
	startIndex, s := marshal.ReadInt(s)
	logLen, s := marshal.ReadInt(s)
	log, s := marshal.ReadSlice[logentry_gk.S](s, logLen, logentry_gk.Unmarshal)

	return S{
		Epoch:      epoch,
		StartIndex: startIndex,
		Log:        log,
	}, s
}
