//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package becomeprimaryargs_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Epoch    uint64
	Replicas []uint64
}

func Marshal(enc []byte, b S) []byte {
	enc = marshal.WriteInt(enc, b.Epoch)

	enc = marshal.WriteInt(enc, uint64(len(b.Replicas)))
	enc = marshal.WriteSlice[uint64](enc, b.Replicas, marshal.WriteInt)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	epoch, s := marshal.ReadInt(s)
	replicasLen, s := marshal.ReadInt(s)
	replicas, s := marshal.ReadSlice[uint64](s, replicasLen, marshal.ReadInt)

	return S{
		Epoch:    epoch,
		Replicas: replicas,
	}, s
}
