//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package proposeargs_gk

import (
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/paxi/reconf/monotonicvalue_gk"
)

type S struct {
	Term uint64
	Val  monotonicvalue_gk.S
}

func Marshal(enc []byte, p S) []byte {
	enc = marshal.WriteInt(enc, p.Term)
	enc = monotonicvalue_gk.Marshal(enc, p.Val)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	term, s := marshal.ReadInt(s)
	val, s := monotonicvalue_gk.Unmarshal(s)

	return S{
		Term: term,
		Val:  val,
	}, s
}
