//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package put_gk

import (
	"github.com/goose-lang/primitive"
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	OpId  uint64
	Key   string
	Value string
}

func Marshal(enc []byte, p S) []byte {
	enc = marshal.WriteInt(enc, p.OpId)
	primitive.AssumeNoStringOverflow(p.Key)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(p.Key))
	primitive.AssumeNoStringOverflow(p.Value)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(p.Value))

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	opId, s := marshal.ReadInt(s)
	keyBytes, s := marshal.ReadLenPrefixedBytes(s)
	key := string(std.BytesClone(keyBytes))
	valueBytes, s := marshal.ReadLenPrefixedBytes(s)
	value := string(std.BytesClone(valueBytes))

	return S{
		OpId:  opId,
		Key:   key,
		Value: value,
	}, s
}
