//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package preparereply_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Success bool
	Log     []uint64
	Pn      uint64
}

func Marshal(enc []byte, p S) []byte {
	enc = marshal.WriteBool(enc, p.Success)

	enc = marshal.WriteInt(enc, uint64(len(p.Log)))
	enc = marshal.WriteSlice[uint64](enc, p.Log, marshal.WriteInt)
	enc = marshal.WriteInt(enc, p.Pn)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	success, s := marshal.ReadBool(s)
	logLen, s := marshal.ReadInt(s)
	log, s := marshal.ReadSlice[uint64](s, logLen, marshal.ReadInt)
	pn, s := marshal.ReadInt(s)

	return S{
		Success: success,
		Log:     log,
		Pn:      pn,
	}, s
}
