//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package cachevalue_gk

import (
	"github.com/goose-lang/primitive"
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	V string
	L uint64
}

func Marshal(enc []byte, c S) []byte {
	primitive.AssumeNoStringOverflow(c.V)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(c.V))
	enc = marshal.WriteInt(enc, c.L)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	vBytes, s := marshal.ReadLenPrefixedBytes(s)
	v := string(std.BytesClone(vBytes))
	l, s := marshal.ReadInt(s)

	return S{
		V: v,
		L: l,
	}, s
}
