//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package finishwrite_gk

import (
	"github.com/goose-lang/primitive"
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"
)

type S struct {
	WriteId uint64
	Keyname string
}

func Marshal(enc []byte, f S) []byte {
	enc = marshal.WriteInt(enc, f.WriteId)
	primitive.AssumeNoStringOverflow(f.Keyname)
	enc = marshal.WriteLenPrefixedBytes(enc, []byte(f.Keyname))

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	writeId, s := marshal.ReadInt(s)
	keynameBytes, s := marshal.ReadLenPrefixedBytes(s)
	keyname := string(std.BytesClone(keynameBytes))

	return S{
		WriteId: writeId,
		Keyname: keyname,
	}, s
}
