//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package getstatereply_gk

import (
	"github.com/goose-lang/std"
	"github.com/tchajed/marshal"

	"github.com/mit-pdos/gokv/vrsm/replica/err_gk"
)

type S struct {
	Err                err_gk.E
	NextIndex          uint64
	CommittedNextIndex uint64
	State              []byte
}

func Marshal(enc []byte, g S) []byte {
	enc = err_gk.Marshal(enc, g.Err)
	enc = marshal.WriteInt(enc, g.NextIndex)
	enc = marshal.WriteInt(enc, g.CommittedNextIndex)
	enc = marshal.WriteInt(enc, uint64(len(g.State)))
	enc = marshal.WriteBytes(enc, g.State)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	err, s := err_gk.Unmarshal(s)
	nextIndex, s := marshal.ReadInt(s)
	committedNextIndex, s := marshal.ReadInt(s)
	stateBytes, s := marshal.ReadLenPrefixedBytes(s)
	state := std.BytesClone(stateBytes)

	return S{
		Err:                err,
		NextIndex:          nextIndex,
		CommittedNextIndex: committedNextIndex,
		State:              state,
	}, s
}
