name: CI

on:
  push:
    branches:
      - main
      - new
  pull_request:
  schedule:
    # every week on Monday at 7am UTC
    - cron: "0 7 * * MON"

jobs:
  test:
    strategy:
      matrix:
        go-version: ["stable"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go get -t ./...
      - name: Check style
        run: |
          gofmt -w .
          git diff --exit-code
      - name: Test
        run: |
          make
