name: CI 

on:
  push:
    branches:
      - main
      - grackle
  pull_request:

jobs:
  update-grackle:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          submodules: true 
      - name: Install protoc
        run: sudo apt-get install protobuf-compiler -y
      - name: Install Go
        uses: actions/setup-go@v5
        with: 
          go-version: "1.22"
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Check Grackle 
        run: |
          ./update-grackle.py
          git diff --exit-code
