//--------------------------------------
// This file is autogenerated by grackle
// DO NOT MANUALLY EDIT THIS FILE
//--------------------------------------

package getrequest_gk

import (
	"github.com/tchajed/marshal"
)

type S struct {
	Key uint64
}

func Marshal(enc []byte, g S) []byte {
	enc = marshal.WriteInt(enc, g.Key)

	return enc
}

func Unmarshal(s []byte) (S, []byte) {

	key, s := marshal.ReadInt(s)

	return S{
		Key: key,
	}, s
}
